import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { Router } from '@angular/router';
import { Base } from '../bases/base';

@Component({
  selector: 'app-mipres',
  templateUrl: './mipres.component.html',
  styleUrls: ['./mipres.component.scss']
})
export class MipresComponent extends Base implements OnInit {
  route: String;
  mipresRole: String; //supplier and delivery
  public mainToken: String = '525FE1ED-00E2-4364-9F5D-7612B8B1E21E';
  public nit: String = '802024817';
  public secondToken: String = '';
  public addressingList: any[] = [];
  public products: any[];

  epsList: any[] = [
    {"CodEPS": "CCF007", "DescEPS":"CAJA DE COMPENSACIÓN FAMILIAR  DE CARTAGENA - COMFAMILIAR CARTAGENA"},
{"CodEPS": "CCF009", "DescEPS":"CAJA DE COMPENSACIÓN FAMILIAR DE BOYACÁ - COMFABOY"},
{"CodEPS": "CCF015", "DescEPS":"CAJA DE COMPENSACION FAMILIAR DE CORDOBA - COMFACOR"},
{"CodEPS": "CCF023", "DescEPS":"CAJA DE COMPENSACIÓN FAMILIAR DE LA GUAJIRA - COMFAGUAJIRA"},
{"CodEPS": "CCF024", "DescEPS":"CAJA DE COMPENSACIÓN FAMILIAR DEL HUILA - COMFAMILIAR HUILA"},
{"CodEPS": "CCF027", "DescEPS":"CAJA DE COMPENSACIÓN FAMILIAR DE NARIÑO - COMFAMILIAR NARIÑO"},
{"CodEPS": "CCF033", "DescEPS":"CAJA DE COMPENSACIÓN FAMILIAR DE SUCRE - COMFASUCRE"},
{"CodEPS": "CCF045", "DescEPS":"CAJA DE COMPENSACIÓN FAMILIAR DEL NORTE DE SANTANDER  - COMFANORTE"},
{"CodEPS": "CCF050", "DescEPS":"CAJA DE COMPENSACIÓN FAMILIAR C.C.F. DEL ORIENTE COLOMBIANO - COMFAORIENTE"},
{"CodEPS": "CCF053", "DescEPS":"CAJA DE COMPENSACIÓN FAMILIAR DE CUNDINAMARCA - COMFACUNDI"},
{"CodEPS": "CCF055", "DescEPS":"CAJA DE COMPENSACION FAMILIAR  CAJACOPI ATLANTICO"},
{"CodEPS": "CCF102", "DescEPS":"CAJA DE COMPENSACIÓN FAMILIAR DEL CHOCÓ - COMFACHOCO"},
{"CodEPS": "CCFC07", "DescEPS":"CAJA DE COMPENSACIÓN FAMILIAR  DE CARTAGENA - COMFAMILIAR CARTAGENA -CM"},
{"CodEPS": "CCFC09", "DescEPS":"CAJA DE COMPENSACIÓN FAMILIAR  DE BOYACÁ - COMFABOY -CM"},
{"CodEPS": "CCFC15", "DescEPS":"CAJA DE COMPENSACION FAMILIAR DE CORDOBA - COMFACOR -CM"},
{"CodEPS": "CCFC20", "DescEPS":"CAJA DE COMPENSACIÓN FAMILIAR DEL CHOCÓ - COMFACHOCO -CM"},
{"CodEPS": "CCFC23", "DescEPS":"CAJA DE COMPENSACIÓN FAMILIAR DE LA GUAJIRA - COMFAGUAJIRA -CM"},
{"CodEPS": "CCFC24", "DescEPS":"CAJA DE COMPENSACIÓN FAMILIAR DEL HUILA - COMFAMILIAR HUILA -CM"},
{"CodEPS": "CCFC27", "DescEPS":"CAJA DE COMPENSACIÓN FAMILIAR DE NARIÑO - COMFAMILIAR NARIÑO -CM"},
{"CodEPS": "CCFC33", "DescEPS":"CAJA DE COMPENSACIÓN FAMILIAR DE SUCRE - COMFASUCRE -CM"},
{"CodEPS": "CCFC50", "DescEPS":"CAJA DE COMPENSACIÓN FAMILIAR C.C.F. DEL ORIENTE COLOMBIANO - COMFAORIENTE -CM"},
{"CodEPS": "CCFC53", "DescEPS":"CAJA DE COMPENSACIÓN FAMILIAR DE CUNDINAMARCA - COMFACUNDI -CM"},
{"CodEPS": "CCFC55", "DescEPS":"CAJA DE COMPENSACION FAMILIAR  CAJACOPI ATLANTICO -CM"},
{"CodEPS": "EAS016", "DescEPS":"EMPRESAS PUBLICAS DE MEDELLIN - DEPARTAMENTO MEDICO"},
{"CodEPS": "EAS027", "DescEPS":"FONDO PASIVO SOCIAL DE LOS FERROCARRILES NACIONALES"},
{"CodEPS": "EPS001", "DescEPS":"ALIANSALUD E.P.S."},
{"CodEPS": "EPS002", "DescEPS":"SALUD TOTAL S.A. "},
{"CodEPS": "EPS003", "DescEPS":"CAFESALUD E.P.S."},
{"CodEPS": "EPS005", "DescEPS":"E.P.S. SANITAS"},
{"CodEPS": "EPS008", "DescEPS":"COMPENSAR E.P.S."},
{"CodEPS": "EPS010", "DescEPS":"EPS Y MEDICINA PREPAGADA SURAMERICANA S.A"},
{"CodEPS": "EPS012", "DescEPS":"COMFENALCO VALLE "},
{"CodEPS": "EPS016", "DescEPS":"COOMEVA E.P.S. S.A."},
{"CodEPS": "EPS017", "DescEPS":"FAMISANAR E.P.S. LTDA - CAFAM - COLSUBSIDIO"},
{"CodEPS": "EPS018", "DescEPS":"SERVICIO OCCIDENTAL DE SALUD - S.O.S. S.A."},
{"CodEPS": "EPS022", "DescEPS":"A.R.S. CONVIDA"},
{"CodEPS": "EPS023", "DescEPS":"CRUZ BLANCA E.P.S."},
{"CodEPS": "EPS025", "DescEPS":"CAJA DE PREVISION SOCIAL Y SEGURIDAD DEL CASANARE - CAPRESOCA E.P.S."},
{"CodEPS": "EPS033", "DescEPS":"SALUDVIDA S.A. E.P.S."},
{"CodEPS": "EPS037", "DescEPS":"NUEVA EPS S.A"},
{"CodEPS": "EPS040", "DescEPS":"SAVIA SALUD E.P.S. -CM"},
{"CodEPS": "EPS041", "DescEPS":"NUEVA EPS S.A. -CM"},
{"CodEPS": "EPS042", "DescEPS":"COOSALUD ENTIDAD PROMOTORA DE SALUD S.A. "},
{"CodEPS": "EPS044 ", "DescEPS":"MEDIMAS EPS S.A.S. CONTRIBUTIVO"},
{"CodEPS": "EPS045", "DescEPS":"MEDIMAS EPS S.A.S. - CM"},
{"CodEPS": "EPS046", "DescEPS":"FUNDACION SALUD MIA EPS"},
{"CodEPS": "EPS048", "DescEPS":"ASOCIACION MUTUAL SER EMPRESA SOLIDARIA DE SALUD EPS-S -MUTUAL SER EPS-S"},
{"CodEPS": "EPSC03", "DescEPS":"CAFESALUD  E.P.S.  S.A. -CM"},
{"CodEPS": "EPSC22", "DescEPS":"EPS CONVIDA -CM"},
{"CodEPS": "EPSC25", "DescEPS":"CAJA DE PREVISION SOCIAL Y SEGURIDAD DEL CASANARE - CAPRESOCA E.P.S. -CM"},
{"CodEPS": "EPSC33 ", "DescEPS":"SALUDVIDA  S.A.  E.P.S.-CM "},
{"CodEPS": "EPSC34", "DescEPS":"CAPITAL SALUD E.P.S. -CM"},
{"CodEPS": "EPSI01", "DescEPS":"ASOCIACIÓN INDÍGENA DEL CESAR Y LA GUAJIRA - DUSAKAWI"},
{"CodEPS": "EPSI02", "DescEPS":"MANEXKA EPSI"},
{"CodEPS": "EPSI03", "DescEPS":"ASOCIACIÓN INDÍGENA DEL CAUCA - AIC"},
{"CodEPS": "EPSI04", "DescEPS":"ANASWAYUU EPSI"},
{"CodEPS": "EPSI05", "DescEPS":"MALLAMAS EPSI"},
{"CodEPS": "EPSI06", "DescEPS":"PIJAOS SALUD EPSI"},
{"CodEPS": "EPSIC1", "DescEPS":"ASOCIACIÓN INDÍGENA DEL CESAR Y LA GUAJIRA - DUSAKAWI -CM"},
{"CodEPS": "EPSIC2", "DescEPS":"MANEXKA EPSI -CM"},
{"CodEPS": "EPSIC3", "DescEPS":"ASOCIACIÓN INDÍGENA DEL CAUCA - AIC -CM"},
{"CodEPS": "EPSIC4", "DescEPS":"ANASWAYUU EPSI -CM"},
{"CodEPS": "EPSIC5", "DescEPS":"MALLAMAS EPSI -CM"},
{"CodEPS": "EPSIC6", "DescEPS":"PIJAOS SALUD EPSI -CM"},
{"CodEPS": "EPSM03", "DescEPS":"CAFESALUD E.P.S. S.A. -CM"},
{"CodEPS": "EPSM33", "DescEPS":"SALUDVIDA S.A. EPS -CM"},
{"CodEPS": "EPSS01", "DescEPS":"ALIANSALUD E.P.S. -CM"},
{"CodEPS": "EPSS02", "DescEPS":"SALUD TOTAL E.P.S. -CM"},
{"CodEPS": "EPSS03", "DescEPS":"CAFESALUD  E.P.S.  S.A."},
{"CodEPS": "EPSS05", "DescEPS":"EPS SANITAS - CM"},
{"CodEPS": "EPSS08", "DescEPS":"COMPENSAR E.P.S. -CM"},
{"CodEPS": "EPSS10", "DescEPS":"EPS Y MEDICINA PREPAGADA SURAMERICANA S.A -CM"},
{"CodEPS": "EPSS12", "DescEPS":"COMFENALCO VALLE -CM"},
{"CodEPS": "EPSS15", "DescEPS":"Salud  Colpatria  E.P.S.-CM"},
{"CodEPS": "EPSS16", "DescEPS":"COOMEVA E.P.S. S.A. -CM"},
{"CodEPS": "EPSS17", "DescEPS":"FAMISANAR E.P.S. LTDA - CAFAM - COLSUBSIDIO -CM"},
{"CodEPS": "EPSS18", "DescEPS":"SERVICIO OCCIDENTAL DE SALUD - S.O.S. S.A. -CM"},
{"CodEPS": "EPSS23", "DescEPS":"CRUZ BLANCA E.P.S. -CM"},
{"CodEPS": "EPSS33", "DescEPS":"SALUDVIDA S.A .E.P.S"},
{"CodEPS": "EPSS34", "DescEPS":"CAPITAL SALUD E.P.S."},
{"CodEPS": "EPSS37", "DescEPS":"NUEVA EPS S.A. -CM"},
{"CodEPS": "EPSS40", "DescEPS":"SAVIA SALUD E.P.S."},
{"CodEPS": "EPSS41", "DescEPS":"NUEVA EPS S.A."},
{"CodEPS": "EPSS42", "DescEPS":"COOPERATIVA DE SALUD Y DESARROLLO INTEGRAL ZONA SUR ORIENTAL DE CARTAGENA - COOSALUD -CM"},
{"CodEPS": "EPSS44", "DescEPS":"MEDIMAS EPS S.A.S. - CM"},
{"CodEPS": "EPSS45", "DescEPS":"MEDIMAS EPS S.A.S. SUBSIDIADO"},
{"CodEPS": "EPSS46", "DescEPS":"FUNDACION SALUD MIA EPS"},
{"CodEPS": "EPSS48", "DescEPS":"ASOCIACION MUTUAL SER EMPRESA SOLIDARIA DE SALUD EPS-S -MUTUAL SER EPS-S"},
{"CodEPS": "ESS002", "DescEPS":"EMPRESA MUTUAL PARA EL DESARROLLO INTEGRAL DE LA SALUD - EMDISALUD ESS"},
{"CodEPS": "ESS024", "DescEPS":"COOPERATIVA DE SALUD Y DESARROLLO INTEGRAL ZONA SUR ORIENTAL DE CARTAGENA LTDA. - COOSALUD E.S.S."},
{"CodEPS": "ESS062", "DescEPS":"ASMET SALUD EPS SAS"},
{"CodEPS": "ESS062", "DescEPS":"ASOCIACIÓN MUTUAL LA ESPERANZA - ASMET  SALUD"},
{"CodEPS": "ESS076", "DescEPS":"ASOCIACIÓN MUTUAL BARRIOS UNIDOS DE QUIBDÓ E.S.S. - AMBUQ"},
{"CodEPS": "ESS091", "DescEPS":"ENTIDAD COOPERATIVA SOLIDARIA DE SALUD DEL NORTE DE SOACHA - ECOOPSOS "},
{"CodEPS": "ESS091", "DescEPS":"EMPRESA PROMOTORA DE SALUD ECOOPSOS EPS S.A.S."},
{"CodEPS": "ESS118", "DescEPS":"EMSSANAR S.A.S."},
{"CodEPS": "ESS118", "DescEPS":"ASOCIACIÓN MUTUAL EMPRESA SOLIDARIA DE SALUD DE NARIÑO - EMSSANAR E.S.S."},
{"CodEPS": "ESS133", "DescEPS":"COOPERATIVA DE SALUD COMUNITARIA - COMPARTA"},
{"CodEPS": "ESS207", "DescEPS":"ASOCIACIÓN MUTUAL SER EMPRESA SOLIDARIA DE SALUD E.S.S."},
{"CodEPS": "ESSC02", "DescEPS":"EMPRESA MUTUAL PARA EL DESARROLLO INTEGRAL DE LA SALUD - EMDISALUD E.S.S. -CM"},
{"CodEPS": "ESSC07", "DescEPS":"ASOCIACIÓN MUTUAL SER EMPRESA SOLIDARIA DE SALUD E.S.S. -CM"},
{"CodEPS": "ESSC18", "DescEPS":"EMSSANAR S.A.S."},
{"CodEPS": "ESSC18", "DescEPS":"ASOCIACIÓN MUTUAL EMPRESA SOLIDARIA DE SALUD DE NARIÑO - EMSSANAR E.S.S. -CM"},
{"CodEPS": "ESSC24", "DescEPS":"COOPERATIVA DE SALUD Y DESARROLLO INTEGRAL ZONA SUR ORIENTAL DE CARTAGENA - COOSALUD E.S.S. -CM"},
{"CodEPS": "ESSC24", "DescEPS":"COOPERATIVA DE SALUD Y DESARROLLO INTEGRAL ZONA SUR ORIENTAL DE CARTAGENA - COOSALUD E.S.S. -CM"},
{"CodEPS": "ESSC33", "DescEPS":"COOPERATIVA DE SALUD COMUNITARIA - COMPARTA -CM"},
{"CodEPS": "ESSC62", "DescEPS":"ASOCIACIÓN MUTUAL LA ESPERANZA - ASMET  SALUD -CM"},
{"CodEPS": "ESSC62", "DescEPS":"ASMET SALUD EPS SAS -CM"},
{"CodEPS": "ESSC76", "DescEPS":"ASOCIACIÓN MUTUAL BARRIOS UNIDOS DE QUIBDÓ E.S.S. - AMBUQ -CM"},
{"CodEPS": "ESSC91", "DescEPS":"EMPRESA PROMOTORA DE SALUD ECOOPSOS EPS S.A.S."}
  ];

  constructor(location: Location, router: Router) { 
    super();
    router.events.subscribe(val => {
      if(location.path().includes("mipres-supplier")){
        this.route = 'Acceso para área de proveedores';
        this.mipresRole = 'supplier';
      }
      if(location.path().includes("mipres-delivery")){
        this.route = 'Acceso para área de dispensación';
        this.mipresRole = 'delivery';
      }
      if(location.path().includes("mipres-admin")){
        this.route = 'Acceso Admin';
        this.mipresRole = 'admin';
      }
    });
  }

  ngOnInit() {
    
  }

}
